name: Deploy and tag

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
  tag:
    name: Tag version
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: commits
      env:
        COMMITS: ${{ toJson(github.event.head_commit.message) }}
      run: echo "$COMMITS"
    - name: Bump version and push tag if not skipped
      if: ${{ !contains(github.event.head_commit.message, '#skip') }}
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
        WITH_V: true