name: Bump version

on:
  workflow_run:
    workflows: ["Fly Deploy"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
        WITH_V: true