name: Bump version

on:
  workflow_run:
    workflows: ["Fly Deploy"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: commits
      env:
        COMMITS: ${{ toJson(github.workflow_run.head_commit) }}
      run: echo "$COMMITS"
    - name: message
      env:
        COMMIT_MESSAGES: ${{ toJson(github.workflow_run.head_commit.message) }}
      run: echo "$COMMIT_MESSAGES"

    - name: Bump version and push tag
      if: ${{ contains(github.workflow_run.head_commit.message, '#skip') }}
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
        WITH_V: true