name: Bump version

on:
  push:
    branches:
      - master

jobs:
  on-success:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: commits
      env:
        COMMITS: ${{ toJson(github.event.commits) }}
      run: echo "$COMMITS"

    - name: Bump version and push tag
      if: ${{ contains(github.workflow_run.head_commit.message, '#skip') }}
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
        WITH_V: true